package com.beanLoyal.backend.push;

import com.beanLoyal.backend.common.ApiException;
import org.springframework.http.HttpStatus;

import java.time.DateTimeException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Pure audience-validation and matching rules used by preview and send, ensuring the count shown
 * to an admin is generated by exactly the same criteria as final delivery.
 */
final class AudienceMatcher {

    private static final int MAX_AGE = 120;
    private static final int MAX_VISIT_DAYS = 3_650;
    private static final ZoneId BUSINESS_ZONE = ZoneId.of("Africa/Casablanca");
    private static final Set<String> KNOWN_LOCATIONS = Set.of("hassan", "agdal", "al irfane");

    private AudienceMatcher() {
    }

    /** Validate filter bounds before Firestore is read. */
    static void validate(PushAudienceFilter filter) {
        if (filter == null || Boolean.TRUE.equals(filter.sendToAll())) {
            return;
        }
        if (filter.minAge() != null && (filter.minAge() < 0 || filter.minAge() > MAX_AGE)) {
            invalid("minAge must be between 0 and " + MAX_AGE);
        }
        if (filter.maxAge() != null && (filter.maxAge() < 0 || filter.maxAge() > MAX_AGE)) {
            invalid("maxAge must be between 0 and " + MAX_AGE);
        }
        if (filter.minAge() != null && filter.maxAge() != null && filter.minAge() > filter.maxAge()) {
            invalid("minAge must not exceed maxAge");
        }
        validateDays(filter.lastVisitWithinDays(), "lastVisitWithinDays");
        validateDays(filter.lastVisitBeforeDays(), "lastVisitBeforeDays");
        if (filter.lastVisitWithinDays() != null && filter.lastVisitBeforeDays() != null
                && filter.lastVisitWithinDays() >= filter.lastVisitBeforeDays()) {
            invalid("lastVisitWithinDays must be less than lastVisitBeforeDays when both are set");
        }
    }

    /** Match one user profile against every active dimension. */
    static boolean matches(AudienceProfile profile, PushAudienceFilter filter, Instant now) {
        if (filter == null || Boolean.TRUE.equals(filter.sendToAll())) {
            return true;
        }
        // Birthday campaigns follow the coffee shop's business date, not UTC. Around local
        // midnight those dates can differ and would otherwise notify members on the wrong day.
        LocalDate today = now.atZone(BUSINESS_ZONE).toLocalDate();
        LocalDate birthday = parseDate(profile.birthday());

        if (filter.minAge() != null || filter.maxAge() != null) {
            if (birthday == null || birthday.isAfter(today)) {
                return false;
            }
            int age = Period.between(birthday, today).getYears();
            if (filter.minAge() != null && age < filter.minAge()) return false;
            if (filter.maxAge() != null && age > filter.maxAge()) return false;
        }
        if (Boolean.TRUE.equals(filter.birthdayToday())
                && (birthday == null || !birthdayMatches(today, birthday))) {
            return false;
        }
        if (!matchesOne(profile.gender(), filter.genders())) return false;
        if (!matchesLocation(profile.address(), filter.locations())) return false;
        if (!matchesOne(profile.topInterest(), filter.interests())) return false;

        Instant lastVisit = profile.lastEarnAt();
        if (filter.lastVisitWithinDays() != null) {
            if (lastVisit == null || lastVisit.isBefore(now.minusSeconds(filter.lastVisitWithinDays() * 86_400L))) {
                return false;
            }
        }
        if (filter.lastVisitBeforeDays() != null && lastVisit != null
                && !lastVisit.isBefore(now.minusSeconds(filter.lastVisitBeforeDays() * 86_400L))) {
            return false;
        }
        return true;
    }

    private static boolean birthdayMatches(LocalDate today, LocalDate birthday) {
        if (today.getMonthValue() == birthday.getMonthValue()
                && today.getDayOfMonth() == birthday.getDayOfMonth()) {
            return true;
        }
        return birthday.getMonthValue() == 2 && birthday.getDayOfMonth() == 29
                && !today.isLeapYear() && today.getMonthValue() == 2 && today.getDayOfMonth() == 28;
    }

    private static LocalDate parseDate(String value) {
        if (value == null || value.isBlank()) return null;
        try {
            return LocalDate.parse(value);
        } catch (DateTimeException ignored) {
            return null;
        }
    }

    private static boolean matchesOne(String value, List<String> accepted) {
        if (accepted == null || accepted.isEmpty()) return true;
        String normalized = normalize(value);
        if (normalized.isEmpty()) return false;
        return accepted.stream().map(AudienceMatcher::normalize).anyMatch(normalized::equals);
    }

    private static boolean matchesLocation(String address, List<String> accepted) {
        if (accepted == null || accepted.isEmpty()) return true;
        String normalizedAddress = normalize(address);
        if (normalizedAddress.isEmpty()) return false;
        boolean isKnown = KNOWN_LOCATIONS.stream().anyMatch(normalizedAddress::contains);
        for (String location : accepted) {
            String normalized = normalize(location);
            if ("other".equals(normalized) && !isKnown) return true;
            if (!normalized.isEmpty() && !"other".equals(normalized) && normalizedAddress.contains(normalized)) {
                return true;
            }
        }
        return false;
    }

    static String normalize(String value) {
        return value == null ? "" : value.trim().toLowerCase(Locale.ROOT);
    }

    private static void validateDays(Integer value, String field) {
        if (value != null && (value < 1 || value > MAX_VISIT_DAYS)) {
            invalid(field + " must be between 1 and " + MAX_VISIT_DAYS);
        }
    }

    private static void invalid(String message) {
        throw new ApiException(HttpStatus.BAD_REQUEST, "INVALID_PUSH_FILTER", message);
    }
}
